name: Deploy Infrastruvture
on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      CI_ROLE:
        required: false
      SSH_KEY_GITHUB_ACTIONS:
        required: true
jobs:
  Infra-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $ {{ inputs.work-dir }}
    steps:
      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.CI_ROLE}}
          aws-region: ${{inputs.aws-region}}
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: install awscli
        run: |
          curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh
          chmod +x install-aws.sh
          ./install-aws.sh "v2" "amd64"
          rm install-aws.sh
          aws sts get-caller-identity
      - name: Terraform format
        run: terraform fmt -check
      - name: init
        run: |
           eval `ssh-agent -s`
           ssh-add - <<< '${{secrets.SSH_KEY_GITHUB_ACTIONS}}'
           terraform init
      - name: validate 
        run: terraform validate
      - name: plan
        run: terraform plan
        #- name: Apply
        #  run: terraform apply --auto-approve   

